export const boardConstants = {
    ADD_REQUEST: 'ADD_BOARD',
    ADD_SUCCESS: 'ADD_BOARD_SUCCESS',
    ADD_FAILURE: 'ADD_BOARD_FAILURE',

    GET_REQUEST: 'GET_BOARD',
    GET_SUCCESS: 'GET_BOARD_SUCCESS',
    GET_FAILURE: 'GET_BOARD_FAILURE',


};
